adds privacy/security section
w3c/html-aria pull request #301
Opened 2021-03-28 18:20 UTC by scottaohara

closes #295

happy to make wording adjustments as needed.

cc @ShivanKaul  @samuelweiler  @LJWatson

2021-03-28 20:51 UTC, stevefaulkner approved these changes

2021-03-28 23:33 UTC, patrickhlauke requested changes

2021-03-28 23:33 UTC, patrickhlauke commented on index.html
> +        Therefor, there are no known privacy or security impacts of this specification, as it defines no new features to introduce potential concern.
Therefor > Therefore

2021-03-29 10:51 UTC, scottaohara commented on index.html
> +        Therefor, there are no known privacy or security impacts of this specification, as it defines no new features to introduce potential concern.
```suggestion
        Therefore, there are no known privacy or security impacts of this specification, as it defines no new features to introduce potential concern.
```

2021-03-29 12:48 UTC, patrickhlauke approved these changes

2021-04-08 15:28 UTC, merged