Editorial: update and expand section 3
w3c/html-aria pull request #441
Opened 2022-12-13 18:27 UTC by scottaohara

This PR removes the redundant mentions of "this section is non-normative".  We did not need this for each sub-section, since the parent section 3 is already marked as non-normative.

This PR clarifies and modifies some of the original examples used in this section, and adds a completely new sub-section indicating that authors still need to respect the rules of the host language - using an invalid nesting example to demonstrate.

closes #259

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/html-aria/pull/441.html" title="Last updated on Dec 14, 2022, 7:35 PM UTC (be65185)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/html-aria/441/12cf419...be65185.html" title="Last updated on Dec 14, 2022, 7:35 PM UTC (be65185)">Diff</a>

2022-12-14 10:45 UTC, stevefaulkner requested changes

2022-12-14 10:45 UTC, stevefaulkner commented on index.html
> +        Author guidance to avoid incorrect and not recommended use of ARIA
Suggest "Author guidance to avoid incorrect use of ARIA"

2022-12-14 10:45 UTC, stevefaulkner commented on index.html
> +          in a rendering and potentially accessibility issues.
"a rendering and potentially accessibility issues."

suggest either
"rendering and potentially accessibility issues."
or
"a rendering issue and, potentially, accessibility issues."

2022-12-14 19:35 UTC, scottaohara commented
thanks for the catches, @stevefaulkner. have updated per your feedback

2023-02-02 10:12 UTC, stevefaulkner approved these changes

2023-02-02 10:12 UTC, merged